// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_QLNhanSu.Models;

#nullable disable

namespace WebAPI_QLNhanSu.Migrations
{
    [DbContext(typeof(QLNhanSu_DbContext))]
    [Migration("20241204024518_UpdateNhanVienTaiKhoan")]
    partial class UpdateNhanVienTaiKhoan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucVu")
                        .HasName("PK__ChucVu__D4639533BA2B82CB");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.ChucVuNhanVien", b =>
                {
                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChucVu_NhanVien", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.HopDongLaoDong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.HasKey("MaHopDong")
                        .HasName("PK__HopDongL__36DD43428AC93BE8");

                    b.HasIndex(new[] { "MaNhanVien" }, "HD_UC_MaNhanVien")
                        .IsUnique()
                        .HasFilter("[MaNhanVien] IS NOT NULL");

                    b.ToTable("HopDongLaoDong", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.Luong", b =>
                {
                    b.Property<int>("BacLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("HeSoCoBan")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("HeSoLuong")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BacLuong")
                        .HasName("PK__Luong__1679C25A34BFF3D9");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("BacLuong")
                        .HasColumnType("int");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChucVu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaPhongBan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaTrinhDoHocVan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA472AA6EA72");

                    b.HasIndex("BacLuong");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaTrinhDoHocVan");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongBan")
                        .HasName("PK__PhongBan__D0910CC81F81B278");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC27104B294E");

                    b.HasIndex(new[] { "MaNhanVien" }, "UC_MaNhanVien")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D105348F16C3E8")
                        .IsUnique();

                    b.HasIndex(new[] { "TenTaiKhoan" }, "UQ__TaiKhoan__B106EAF815D63A8F")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.TrinhDoHocVan", b =>
                {
                    b.Property<string>("MaTrinhDoHocVan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoHocVan1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrinhDoHocVan");

                    b.HasKey("MaTrinhDoHocVan")
                        .HasName("PK__TrinhDoH__B3AD801380FB4056");

                    b.ToTable("TrinhDoHocVan", (string)null);
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.ChucVuNhanVien", b =>
                {
                    b.HasOne("WebAPI_QLNhanSu.Models.ChucVu", "MaChucVuNavigation")
                        .WithMany()
                        .HasForeignKey("MaChucVu")
                        .IsRequired()
                        .HasConstraintName("FK__ChucVu_Nh__MaChu__5629CD9C");

                    b.HasOne("WebAPI_QLNhanSu.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__ChucVu_Nh__MaNha__571DF1D5");

                    b.Navigation("MaChucVuNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.HopDongLaoDong", b =>
                {
                    b.HasOne("WebAPI_QLNhanSu.Models.NhanVien", "MaNhanVienNavigation")
                        .WithOne("HopDongLaoDong")
                        .HasForeignKey("WebAPI_QLNhanSu.Models.HopDongLaoDong", "MaNhanVien")
                        .HasConstraintName("FK__HopDongLa__MaNha__59FA5E80");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.NhanVien", b =>
                {
                    b.HasOne("WebAPI_QLNhanSu.Models.Luong", "BacLuongNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("BacLuong")
                        .HasConstraintName("FK__NhanVien__BacLuo__5165187F");

                    b.HasOne("WebAPI_QLNhanSu.Models.PhongBan", "MaPhongBanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK__NhanVien__MaPhon__52593CB8");

                    b.HasOne("WebAPI_QLNhanSu.Models.TrinhDoHocVan", "MaTrinhDoHocVanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTrinhDoHocVan")
                        .HasConstraintName("FK__NhanVien__MaTrin__534D60F1");

                    b.Navigation("BacLuongNavigation");

                    b.Navigation("MaPhongBanNavigation");

                    b.Navigation("MaTrinhDoHocVanNavigation");
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.TaiKhoan", b =>
                {
                    b.HasOne("WebAPI_QLNhanSu.Models.NhanVien", "MaNhanVienNavigation")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("WebAPI_QLNhanSu.Models.TaiKhoan", "MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan__MaNhan__0A9D95DB");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.Luong", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.NhanVien", b =>
                {
                    b.Navigation("HopDongLaoDong");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebAPI_QLNhanSu.Models.TrinhDoHocVan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
